### ISSUE TITLE
Full tests are failing on windows

### ISSUE THREAD

**Issue by orium** [rust-dev-tools/rust-semverver#105]
These tests seem to be failing on windows (but I only ran them on Travis).

These test are now disabled on Travis (see 26073be).

**Comment by ibabushkin** [comment]
From travis' build output it looks like there is some path issue going on. I'll see whether it's indeed that simple.

**Comment by ibabushkin** [comment]
Okay, I found some more bugs, I hope that I have a fix though. We'll find out soon enough.
