### ISSUE TITLE
JSON output format

### ISSUE THREAD

**Issue by theduke** [rust-dev-tools/rust-semverver#108]
I'd love to build a CI bot that integrates with Github/Gitlab and warns about semver changes in pull requests.

To do that, semver would need to be exposed as a library. 
There currently is a library published, but it doesn't seem to be intended for actual use.

How easy would this be with the current state of the code base?

**Comment by ibabushkin** [comment]
Pretty easy, just some code movement I suppose. Do you have specific requirements for the interface?

**Comment by theduke** [comment]
Ideally: 

```rust
let changes: ChangeSet = semverver::analyse_crate("/path/to/crate").unwrap();
```

**Comment by theduke** [comment]
Actually, thinking about it, and considering that `semverver` is probably quite closely tied to the compiler, a `json` output format would probably be a better option.

`cargo semver --format=json`.

**Comment by ibabushkin** [comment]
Alright, I'll draft something up -- should be easy since we already transitively depend on `serde`.

**Comment by theduke** [comment]
Awesome, thanks!
If you are busy I can take a look it at as well, but obviously it'll be faster for you.

**Comment by ibabushkin** [comment]
Alright, I've created a branch with optional JSON-formatting of change output. Check out `json_out` for details. The limitation right now is that span info is not included, because the compiler machinery is a bit clever and refers to specific structures in memory. Do you need source spans for your bot?

Other than that, all info is included. All sequences in the output are of pseudorandom order, if that is an issue for you, let me know (but I don't think it should be).

**Comment by theduke** [comment]
Awesome, cheers!
Random order is not a bother. 
Missing spans are though. Reporting changes without any idea where they are is a bit suboptimal.
A simple file+line for a change would be enough though.

**Comment by ibabushkin** [comment]
Alright, I'll see if I can extract range info properly, that should be possible. You still won't be able to mimic compiler output, but maybe that's not what you want, i. e. the bot might be more useful if it comments on a diff. Just an idea, I'll come back when I have a solution.

**Comment by theduke** [comment]
Yeah precise ranges or a nice change diff really aren't important here, just a a file and line so I can link to the file.

Also, I owe you a beer.

**Comment by ibabushkin** [comment]
Commit eb8a45d now has span serialization (including precise ranges, those were easy to add). Please test for yourself whether you're happy with the functionality, my tests didn't bring up anything I didn't expect. I'll write some docs for the format, too.

> Also, I owe you a beer.

:)

**Comment by ibabushkin** [comment]
If you're happy with this feature in its current form, I'll merge it into master and make a release.

**Comment by ibabushkin** [comment]
I merged it into master now, as the feature seems stable. No release yet, but it will be included in the next.

**Comment by ibabushkin** [comment]
New release contains this for sure.
