### ISSUE TITLE
internal error: entered unreachable code in traverse.rs:742

### ISSUE THREAD

**Issue by kornelski** [rust-dev-tools/rust-semverver#109]
When running `cargo semver` on `rmpv` project https://github.com/3Hren/msgpack-rust/tree/master/rmpv I get the following error:

> thread 'rustc' panicked at 'internal error: entered unreachable code', semverver-0.1.42/src/traverse.rs:742:29

**Comment by ibabushkin** [comment]
Alright, I was able to reproduce the issue. I'll have a look and report back when a fix is available. Thanks for the report!

**Comment by ibabushkin** [comment]
The newest release on crates.io fixes this issue, thank you for your patience.
