### ISSUE TITLE
ICEs on specific type checks.

### ISSUE THREAD

**Issue by ibabushkin** [rust-dev-tools/rust-semverver#28]
This causes a crash, no matter whether `Def` is a trait or an ADT (different crashes each time, however).

```pub type Something<'a> = FnMut(Def) -> bool + 'a;```

More specifically, all traits which desugar to something like

```SomeTrait<A, B=Abc>``` cause this problem.

**Comment by ibabushkin** [comment]
The root cause are `Fn` trait objects.

**Comment by orium** [comment]
@ibabushkin It seems you fixed this already :)

**Comment by ibabushkin** [comment]
Oh, the issue didn't get closed (and I didn't get any notifications for like a year)
