### ISSUE TITLE
incompatible changes reported against the same code

### ISSUE THREAD

**Issue by jrmuizel** [rust-dev-tools/rust-semverver#37]
When I run cargo semver against a checkout of core-foundtion-sys that matches the current crate I get a bunch of errors like:
```
error: breaking changes in `CFURLSetResourcePropertyForKey`
   --> /Users/jrmuizel/src/core-foundation-rs/core-foundation-sys/src/url.rs:146:5
    |
146 |     pub fn CFURLSetResourcePropertyForKey(url: CFURLRef, key: CFStringRef, value: CFTypeRef, error: *mut CFErrorRef) -> Boolean;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = warning: type error: expected enum `libc::c_void`, found a different enum `libc::c_void` (breaking)
```

**Comment by ibabushkin** [comment]
Hm, this suggests that a few specific internals behave incorrectly. Actually, other bug reports point towards a similar underlying problem. I'll have a look.

**Comment by ibabushkin** [comment]
It seems to me that no crates exhibit this problem anymore with modern versions of rust-semverver. While I am not entirely sure, I'll close this for now.
