### ISSUE TITLE
Distinguish between hard breaking changes and soft breaking changes

### ISSUE THREAD

**Issue by jrmuizel** [rust-dev-tools/rust-semverver#58]
Sometimes a crate wants to have slightly loser definition of breaking changes. i.e. changes are unlikely to break consumers. This can include things like adding a function to an impl.

@kvark

**Comment by ibabushkin** [comment]
In fact, the tool has a notion of "technically" breaking changes. These are pretty much what you describe -- changes that only break consumers doing very unusal things with the interface. This feature isn't exactly configurable so far. Would a command line switch to treat such changes as non-breaking solve your issue? If not, what other features do you have in mind?

**Comment by kvark** [comment]
Having such a switch sounds like a good start. Ultimately, we may need to end up with some sort of a config file describing which breakage types are acceptable.

**Comment by ibabushkin** [comment]
However, I should add that currently adding an item to an associated impl is such a technically breaking change.

**Comment by gnzlbg** [comment]
I've implemented a flag that doesn't warn for `NonTechnical` changes. I've called it `--api-guidelines`, but now that it works I'd like to gather feedback on how do you think that this feature should be implemented. E.g. would a flag `--silence-non-technical-breaking-changes` be a good way to proceed here, or do you prefer a way to control more precisely what's silenced e.g. `--silence=patch,...` ? 

For me, a flag to silence "soft" breaking changes (or breaking changes that are considered by the API guidelines group as "non breaking"), would be personally already enough.
