### ISSUE TITLE
Add the ability to query exposed types

### ISSUE THREAD

**Issue by jrmuizel** [rust-dev-tools/rust-semverver#63]
I'm not sure this is the best place for this, but it would be handy to have a tool that given a crate you could check which types we're exposed by that crate.

E.g. The core-text and cocoa crates expose some types from the core-graphics crate. It would be nice to be able to have a program that prints out whether any types are exposed and what they are.

**Comment by ibabushkin** [comment]
Hm, I see your point and I think that can be done with reasonable complexity in or using code from rust-semverver. Unfortunately, I'm currently very short on time, but I'll get back to this later this year. Or someone could pick this up -- I'll be glad to provide pointers.

**Comment by ibabushkin** [comment]
Alright, a reasonably polished (but kind of hacky under the hood) version of this feature is available in semverver v0.1.35.
