### ISSUE TITLE
Error loading shared libs

### ISSUE THREAD

**Issue by mygnu** [rust-dev-tools/rust-semverver#69]
I'm not able to run `cargo semver` on my project lib. Ubuntu OS
i get the following error
```bash
Finished dev [unoptimized + debuginfo] target(s) in 1m 55s
rust-semverver: error while loading shared libraries: librustc_driver-3ef790569e54b48c.so: cannot open shared object file: No such file or directory

rustc --version && cargo --version
rustc 1.29.1 (b801ae664 2018-09-20)
cargo 1.29.0 (524a578d7 2018-08-05)
rustup --version
rustup 1.13.0 (ea9259c1b 2018-07-16)
```

**Comment by ibabushkin** [comment]
Judging by the version output of your rustc and cargo, you are not running a nightly. Currently, the tool does not support that. Running with a nightly should work, please try that and report back.

**Comment by ibabushkin** [comment]
Have you recompiled `rust-semverver`? I should have mentioned that is required. To avoid further confusion: The crate needs nightly features because it uses code from the compiler (which you can't do on stable) and requires the compiler version it is run with to match the one it was built with as well, for the same reasons. So, since you're running `rustup`, the following update sequence should leave you with a working version:

```sh
$ rustup update nighly
$ cargo install -f semverver
```

Please confirm how that works out for you and thanks for being patient.

**Comment by carlosb1** [comment]
I have the same error following the installation steps, I would appreciate any help: 

```
$ rustup update nightly
$ cargo +nightly install --git https://github.com/rust-dev-tools/rust-semverver --force
```

and it doesn't work...: 

```
cargo semver -S tokio:0.1.16 -C tokio:0.1.17
current_rlib: "/....../target/debug/deps/libtokio-6e5b3e73c8e19b84.rlib"
stable_rlib: "/......./target/debug/deps/libtokio-e640d8ce791ace61.rlib"
rust-semverver: error while loading shared libraries: librustc_driver-0c086decc5a4e8ff.so: cannot open shared object file: No such file or directory
error: rustc-semverver errored
```

**Comment by ibabushkin** [comment]
Hm, very odd. I just checked on multiple boxes using the somewhat more useful command

```
cargo +nightly install semverver -f
```

and that worked a treat to check the tokio versions in your example (with the most current nightly). Maybe try that for now

**Comment by carlosb1** [comment]
I tried with your command  and it throws the same error. Furthermore, I tried with other libs (time crate) and the result is the same.. I will  use docker in order to set up a new environment.

**Comment by ibabushkin** [comment]
That is certainly an option. Can you check in `~/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/` what libs are around? That could help pinpoint whether it's a path related issue or a `rust-semverver` compiled against the wrong toolchain.

**Comment by carlosb1** [comment]
Here my ouput:

```
➜  tokio git:(develop) ls ~/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/
libarena-80a5fefb1bc1eaeb.so                  librustc_metadata-89567dec8e737ad1.so
libfmt_macros-d2b47fd646b658e5.so             librustc_mir-e2e842a0d86548a9.so
libgraphviz-d45c93d2bedecb09.so               librustc_passes-73df9456ab033ec5.so
liblibtest-02baa459a66e9480.so                librustc_plugin-4c266e87622f843e.so
libLLVM-8-rust-1.35.0-nightly.so              librustc_privacy-54ab21c3fbbd7f35.so
librustc-72e73271bcece31c.so                  librustc_resolve-fde1f6f3be1eee66.so
librustc_allocator-9da4a6034aeac532.so        librustc_save_analysis-fc892a5ed7caab0a.so
librustc_borrowck-426a0892212a0fd9.so         librustc_target-38ce3283a102bea7.so
librustc_codegen_ssa-af2acee88712b02f.so      librustc_term-30b38107aef2ed06.so
librustc_codegen_utils-c9b8454290f37769.so    librustc_traits-7840291d645fd3fd.so
librustc_cratesio_shim-f667f9cea6428342.so    librustc_typeck-4c5eabf6145b0a2e.so
librustc_data_structures-6b2a166b4b43bdcd.so  libserialize-c0813809edf53685.so
librustc_driver-3837fdf07f3bf3a3.so           libstd-7b4eb433be23f2b8.so
librustc_errors-2605fe344ec150d3.so           libsyntax-b1c921312084e1a2.so
librustc_fs_util-98f1cac9fc892a88.so          libsyntax_ext-afc071f8db0345a5.so
librustc_incremental-cd49354f7978f6b6.so      libsyntax_pos-fb52a8fa7b490099.so
librustc_interface-c4b9a47ef7c09a29.so        libtest-ab751eb2f87a3410.so
librustc_lint-f68d61f851ac353a.so             rustlib
librustc_macros-bd87a9217252a973.so
```

It uses rust 1.35, as far as I know, it is all correct.

**Comment by carlosb1** [comment]
with the docker image I had the same problem... 5. I will think how to find the problem

**Comment by ibabushkin** [comment]
Judging by the output, the rlibs looked up at startup have the wrong hash. Are you absolutely sure the nightly you have installed is the one used for building (and running) semverver? Since we depend on compiler internals, that is required. If this is reproducible in docker, could you provide a dockerfile for reproduction? Then I can try to help debugging this, as I expect rather ugly details to pop up.

**Comment by carlosb1** [comment]
My fault....
 ➜  ~ rustc -V
rustc 1.33.0 (2aa4c46cf 2019-02-28)

I am not using the nightly version (1.35)... I suppose I am beginner in rust yet... I typed: 
`rustup default nightly` (use nightly by default) and it works perfectly.

Anyway, if you are interested the the docker image that I used:
```
FROM rust:1.31
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY . .
```

**Comment by ibabushkin** [comment]
Oh, alright! I guess I'll make the README a bit clearer then :)
